name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # Устанавливаем URL для доступа к репозиторию через SSH
          git remote set-url origin git@github.com:hiperonsky/Margarine6.git
          
          # Пуллим последние изменения
          git pull origin main
          
          # Подключаемся к серверу и выполняем команды деплоя
          ssh root@2.59.183.62 "cd /root/Margarine6_bot && git pull origin main && ./deploy.sh"