name: Deploy

on:
  push:
    branches:
      - main  # Запускать workflow при push в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no root@2.59.183.62 "cd /root/Margarine6_bot && git remote set-url origin git@github.com:username/Margarine6.git && git pull origin main && ./deploy.sh"