name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # Создаем папку .ssh
          mkdir -p ~/.ssh

          # Удаляем старый файл known_hosts (если существует)
          rm -f ~/.ssh/known_hosts

          # Добавляем приватный ключ
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Добавляем GitHub в known_hosts с подробным выводом ошибок
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          # Проверяем содержимое файла known_hosts
          cat ~/.ssh/known_hosts

          # Убедимся, что ключи добавлены корректно
          ssh -T git@github.com

          # Переход к репозиторию и pull
          git remote set-url origin git@github.com:hiperonsky/Margarine6.git
          git pull origin main

          # Выполнение deploy.sh через SSH
          ssh root@2.59.183.62 "cd /root/Margarine6_bot && git pull origin main && ./deploy.sh"
