name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Добавляем GitHub в known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Убедитесь, что используете SSH URL репозитория
          git remote set-url origin git@github.com:hiperonsky/Margarine6.git

          # Пулл из репозитория
          git pull origin main

          # Перезапуск бота
          ssh root@2.59.183.62 "cd /root/Margarine6_bot && git pull origin main && ./deploy.sh"
